# -*- sh -*-

CONFIG_HOME=$(dirname ${BASH_SOURCE[0]})

# Source basic functions
source ${CONFIG_HOME}/bashrc_functions.bash
source ${CONFIG_HOME}/functions.bash

# Source global definitions
source_one /etc/bashrc

add_path $HOME/bin
add_path $HOME/bin/git

# Specify the editor based on the availability of emacs 23
eclient_version=$(emacsclient --version 2>&1)
if [ "${eclient_version#emacsclient 23}" != "$eclient_version" ]; then
    export EDITOR='emacsclient -t -a ""'
else
    export EDITOR='emacs -nw'
fi
export GIT_EDITOR="${EDITOR}"
export SVN_EDITOR="${EDITOR}"

# Env variables for terminal colors
source_one ${CONFIG_HOME}/term_colors

# Grep
export GREP_OPTIONS='--color=auto'

# Python Interactive: see http://valueerror.wordpress.com/2009/11/03/python-shell-history-autocompletion-and-rc-file/
export PYTHONSTARTUP="${CONFIG_HOME}/../python/pythonrc"

# History Tuning
# Colon-delimited list of patterns which should be excluded from being
# stored in bash history. There's also the special pattern '&', which
# suppresses duplicate entries (very useful!).
export HISTIGNORE="&:ls:[bf]g:exit:"
shopt -s histappend

# Navigation
shopt -s cdspell
shopt -s cdable_vars

# Aliases
source_one ${CONFIG_HOME}/bash_aliases

# Completion: (somewhat in sync with aliases)
source_one ${CONFIG_HOME}/completion/completion.bash

# Autojump: a package that keeps track of commonly used directories
# (jumpstat) and provides a command for jumping to a fuzzy match (j)
source_one ${CONFIG_HOME}/autojump/autojump.bash

# Shell Prompt
GIT_PS1_SHOWDIRTYSTATE="1"
GIT_PS1_SHOWUPSTREAM="auto"

# Set up the prompt
REV_PROMPT=\
'$(if [ -e .svn ]; then echo " r$(svn info | grep Revision | cut -d\  -f2)"
   else
     __git_ps1;
   fi
)'

PS1='\[\033k\033\\\]' # this little bit of insanity lets screen read the title of the running program
export PS1=$PS1"$MG\u@\h$MB$REV_PROMPT $MW\w$R> $N"

# a reasonable default might be:
# export PS1='[\u@\h \W]\$ '
