# -*- sh -*-

# Section: Editing
alias     e="$EDITOR"
alias    em="emacs"
alias    ec="emacsclient -c --alternate-editor=''"
alias   ebc="emacs -batch -f batch-byte-compile"

# Section: Git
alias     g="git"
alias    gr="grep -ri"
alias   gdc="git diff -U6 --cached"
alias   grn="grep -rin"
alias   grl="grep -ril"
alias   grv="grep -v"
# more git aliases are set up, along with completion, in git-completion-eletuchy.bash

# Section: SVN
alias   sup="svn up"
alias   sin="svn commit"
alias    sd="svn diff -x \"-U6\" --diff-cmd diff"

# Section: Navigation

alias     u="cd .."
alias    u2="cd ../.."
alias    u3="cd ../../.."

# Section: ls
ls --version &> /dev/null
if [ $? -eq 0 ] ; then
    alias    ll="ls -alh --color=tty"
else
    alias    ll="ls -alh"
fi

# Section: Uncategorized
alias  sssh="sudo ssh"
alias   ssh="ssh -A"

alias     l="less"
alias    lr="less -R"

alias   wcl="wc -l"

alias aliasreload="source ${CONFIG_HOME}/bash_aliases"
alias rebash="source ~/.bash_profile"

# Platform Specific / Sensitive Aliases
source ~/.alias
