# -*- sh -*-

CONFIG_HOME=$(dirname ${BASH_SOURCE[0]})

# Source basic functions
source ${CONFIG_HOME}/bashrc_functions.bash
source ${CONFIG_HOME}/functions.bash

# Source global definitions
source_one /etc/bashrc

add_path $HOME/bin
add_path $HOME/bin/git

# Specify the editor based on the availability of emacs 23
eclient_version=$(emacsclient --version 2>&1)
if [ "${eclient_version#emacsclient 23}" != "$eclient_version" ]; then
    export EDITOR='emacsclient -t -a ""'
else
    export EDITOR='emacs -nw'
fi
export GIT_EDITOR="${EDITOR}"
export SVN_EDITOR="${EDITOR}"

# Autojump: a package that keeps track of commonly used directories
# (jumpstat) and provides a command for jumping to a fuzzy match (j)
source ${CONFIG_HOME}/autojump/autojump.bash
